DECLARE @LOTNO VARCHAR(250),@STOKADI VARCHAR(250),@BIRIMI VARCHAR(20),@TOPMIKTAR FLOAT, @SABLON VARCHAR(MAX), @EMAIL VARCHAR(50);  -- değişkenleri tanımladım.

CREATE TABLE #TMP(LOTNO VARCHAR(250),STOKADI VARCHAR(250),BIRIMI VARCHAR(20),TOPMIKTAR FLOAT) -- Geçici tablo oluşturdum. Geçici tabloda basacağım verileri alan olarak açtım.


/* SORGULARI KENDİNİZE GÖRE DÜZENLEYEBİLİRSİNİZ. AKINSOFT veritabanına göre uyarlanmıştır.*/

INSERT INTO #TMP    -- INSERT BASICAM BU TABLOYA 
---------- #TMP GEÇİCİ TABLOSUNA VERİYİ BASACAĞI SELECT DEĞERLERİNİ GÖNDERDİM.
SELECT * FROM (SELECT FH.STOKKODU,FH.STOK_ADI,FH.BIRIMI,SUM(dbo.SAYIYUVARLA1(MIKTARI,3,0)) TPL_MIKTAR FROM FATURA F
JOIN FATURAHR FH ON (FH.BLFTKODU=F.BLKODU) 
JOIN STOK S ON (S.BLKODU=FH.BLSTKODU)
JOIN CARI C ON (C.BLKODU=F.BLCRKODU) WHERE F.BLKODU>0 AND FATURA_DURUMU NOT IN (7) 
 AND DATEADD(DAY,DATEDIFF(DAY,0,F.TARIHI),0)>=FORMAT(GETDATE(), 'dd.MMM.yyyy', 'en-us')
 AND DATEADD(DAY,DATEDIFF(DAY,0,F.TARIHI),0)<=FORMAT(GETDATE(), 'dd.MMM.yyyy', 'en-us')
 AND FATURA_DURUMU IN(5,6,7) AND F.SILINDI='0' AND COALESCE(OZELALANTANIM_15,0) IN(0) AND F.OZEL_KODU='+' AND F.IPTAL='0'
GROUP BY F.SUBE_KODU,FH.BLSTKODU,FH.STOKKODU,FH.STOK_ADI,FH.BIRIMI ) SNC


SET NOCOUNT ON;

-- şablonu set ettim ve HTML TAGLERINI OLUŞTURDUM
SET @SABLON='<html><body><b>'+(SELECT convert(varchar, getdate(), 104)) +' Tarihli Üretimi tamamlanmamış Lot Raporu</b><br><br><table border=1>'		
WHILE ((SELECT COUNT(*) FROM #TMP)>0) -- DÖNGÜYE BAĞLADIM VE YUKARIDAKİ GEÇİCİ TABLO KAYIT TOPLAMINI KONTROL EDEREK DÖNDÜRDÜM.
BEGIN   
	SET @LOTNO = (SELECT TOP 1 LOTNO FROM #TMP ORDER BY LOTNO DESC)
	SET @STOKADI = (SELECT TOP 1 STOKADI FROM #TMP ORDER BY LOTNO DESC)
	SET @BIRIMI = (SELECT TOP 1 BIRIMI FROM #TMP ORDER BY LOTNO DESC)
	SET @TOPMIKTAR = (SELECT TOP 1 TOPMIKTAR FROM #TMP ORDER BY LOTNO DESC)
	/* TABLO VERİLERİNDEN EN ÜSTTEKİ KAYITI DEĞİŞKENLERE DAĞITTIM.  */

	SET @SABLON+= '<tr><td><b> Lot Numarası </b></td><td>' +  cast(@LOTNO as varchar) + 
				 '</td><td><b> Stok Adı  </b></td><td>' +  @STOKADI +
				 '</td><td><b> Birimi  </b></td><td>'+  @BIRIMI +
				 '</td><td><b> Miktar  </b></td><td>' +  cast (@TOPMIKTAR as varchar)+ '</td></tr>'; /* HTML TAGLERINE BU DEĞİŞKENLERİ BASTIM */
		
	DELETE FROM #TMP WHERE LOTNO=@LOTNO  /* Belirlediğim lot numarasını sildirdim. Döngüye devam ettirdim. */
END


SET @SABLON+= +' </table></body></html>'    /* HTML TAGLERINI KAPATTIM. */ 
DECLARE @GEN_VALUE2 BIGINT,@GEN_VALUE3 BIGINT   /* GENERATÖR VALULARINI TANIMLADIM */
EXECUTE SP_GEN_ID @GEN_NAME=MAILSMS_KUYRUK_GEN,@INCREMENT=1,@GEN_VALUE=@GEN_VALUE2 OUTPUT /* MAILSMS KUYRUK TABLOSUNA GENERATÖR EXECUTELADIM. */
INSERT INTO WOLVOX8_SIRKET.dbo.MAILSMS_KUYRUK (BLKODU,SIRKETKODU,CALISMA_YILI,MODUL,BLMASKODU,KAYDEDEN,GONDERIM_TIPI,ALICI_ADRES,KONU,SABLON) 
VALUES(@GEN_VALUE2,'FEYAS',2021,'Tamamlanmayan Lotlar',63,'sa',1,'mertay@arelteknoloji.net','Üretimi tamamlanmamış Lot Raporu',@SABLON)
/*INSERTU BASTIM  */
DROP TABLE #TMP
 /*TEMP TABLOYU DROPLADIM*/
